DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS question;
CREATE TABLE question (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  cat_number INTEGER NOT NULL,
  category VARCHAR(30) NOT NULL,
  question TEXT NOT NULL,
  correct_answer VARCHAR(50) NOT NULL,
  answer1 VARCHAR(50) NOT NULL,
  answer2 VARCHAR(50) NOT NULL,
  answer3 VARCHAR(50) NOT NULL,
  answer4 VARCHAR(50) NOT NULL
);